### PR TITLE
0.59

### PR DESCRIPTION
**Pull request by axm**
Hi everyone! 

I have commented some of the code and tried to make it clearer wherever possible. I also moved some methods or variables around a source file if they seemed not to belong to the place they were originally in. I read the article about the source code on openlierox.net, but please let me know if I did anything wrong.

Cheers,
magn3to

### CODE REVIEW

**Comment by albertz** [comment]
Sorry if some of my comments may sound harsh, that is totally not my intention. :) I just want to be very exact about how we like to have the code. I hope this is helpful. If you have any question, just ask!

Btw., do you know how to `git rebase -i`? Because you probably need to do that before I can merge this in. This is to keep the history somewhat clean. Otherwise we would end up with many commits by you and then again some commits by me which undo your changes (because of what I wrote in my comments) and that looks just ugly and make it hard to see the real changes/improvements.

**Comment by albertz** [comment]
I hope, after all my comments, you got a good idea about how we would like to have the code and commits. :)

I also hope you don't feel depressed about the many complaints. It looks like you put a lot of effort into it and when resolving these few issues I commented about, I think this can make some good progress.

**Comment by axm** [comment]
Thanks for the feedback, albertz, it is of great help - and probably pain, for you. But things are much, much clearer now. I got used to that ridiculous amount of commenting from my University, where we lost marks if we didn't comment properly every single method. Now I realize sometimes it looks ridiculous. There were also some changes I mistakenly commit, I will be more careful in the future and try not to rush.

I will also look into git rebase -i. Cheers!

**Comment by albertz** [comment]
Hey, you didn't really went through all the comments I made. There are still many commits here which are either wrong (see e.g. the comments from Karel) or shouldn't be there at all (such as test commits, etc.).

I would suggest that we close this one here, you checkout to the official 0.59 branch and you do only some small changes step by step. Best would be to ask me after every single step.

**Comment by axm** [comment]
Thanks karelp for your comments!

I moved a while ago and I won't have an internet connection until the 5th of
August so I can't reply to all your comments these days, albertz, but I read
them all once you posted them. I have already checked out the branch and I
will let you know about every potential commit.

**Comment by albertz** [comment]
Ah ok. You can also work offline on OLX, of course. Git is very good for that.

If you want to do that, I would suggest to take some extra work to make the merging for us easier. By that, I mean that you should start a new branch for every single piece you are working on. E.g. like this:

`git checkout 0.59 -b new-stuff-nr1` - then work on it and make 1 or more commits - then `git checkout 0.59 -b new-stuff-nr2` - etc.

Then later, when you have Internet again, you push all of them (`git push --all` I think) and you can make pull requests for every single branch.

If you keep them as small as possible, we can merge exactly those in which are fine and comment on the rest about the problems.

This means some extra work (because you have to create a lot of branches) but it will make it easier after all for both of us. Later on, when you are a bit more experienced about how we work on the OLX code, this is also not really necessary anymore.

**Pull request merged**
