### PR TITLE
Fix compilation error with Boost 1.69

### PR DESCRIPTION
**Pull request by JiPRA**

### CODE REVIEW

**Comment by albertz** [comment]
Signals2 is header only?
Also, as I understand it, it has a different namespace (`boost::signals2`), so some code changes would also be needed? Otherwise I think we still use the old Boost signals.

**Comment by JiPRA** [comment]
Yes, signals2 is header-only, unlike the old signals. CMake cannot find the needed boost_signals libraries with Boost v1.69.0, apparently because signals has become completely obsolete. You are probably right about further code changes but at least the game compiles and works with the newer Boost libraries now. If a backward compatibility with older Boost versions is desired, maybe the files could include some conditional structures to handle these cases? Possibly as easy to do as it sounds but likely still beyond my free time and fairly limited coding skills :) In any case, these are the bare minimum changes for the code to compile successfully on a up-to-date, rolling release Linux distro.

**Comment by albertz** [comment]
My question was: Why does it work? If there is some `boost::signals` in the code, it cannot work with Signals2. Maybe it's completely obsolete? Why do you need the added `#include`. Did you try without? We don't use `boost::signals2` anywhere. So why do you want to import it?

**Comment by JiPRA** [comment]
The following two source code files contain the string ``boost::signals``:

1. ./include/DeprecatedGUI/**CCombobox.h**:
   **boost::signals2**::signal<void (const GuiListItem::Pt&)> OnChangeSelection;
2. ./src/game/**Game.h**:
   **boost::signals2**::signal<void()> prepareCallbacks;

So, it turns out the code is ready for Signals2. Here is my bash output without any changes to the source files:
https://tinyurl.com/y77jdbtb

Here is the output with changes to only CMake file (**CMakeOlxCommon.cmake**):
https://tinyurl.com/y7lfdljy

Finally, here is the output with changes to both of the files (**CMakeOlxCommon.cmake** and **CScriptableVars.h**):
https://tinyurl.com/yaqs6qu3

With both changes, the build process would have completed without issues but I aborted the process early on. You have probably already read this but here is a link to Signals2 API changes:
https://www.boost.org/doc/libs/1_69_0/doc/html/signals2/api_changes.html

**Comment by albertz** [comment]
Hm, ok, it seems then I was using already signals2 before. But the change in CScriptableVars.h is strange. The error which you had before seems somewhat unrelated.
Anyway, will merge this in for now. Will maybe update later myself if there are problems with it.
Thanks for your help!

**Pull request merged**
